use details;
SELECT distinct department from student;
create table department1(dep_id int,dep_name varchar(20),id int,loc_id int);
select * from department;
alter table department add dep_name varchAR(20);
drop table department1;
select * from department1;
create table department1(dep_id int,dep_name varchar(20),id int,loc_id int);
alter table department1 drop column id;
insert into department1 values(122,'MCA',57);
insert into department1 values(167,'CS',54);
insert into department1 values(134,'MATHS',53);
insert into department1 values(124,'PHYSICS',58);
alter table department1 add primary key (dep_id);
describe department1;
SELECT student_name from student union  select dep_name from department1;
alter table student add primary key (id);
describe student;
alter table student add foreign key (id) references department1(dep_id);